import { Metadata } from "next";
import AuthNavbar from "./_components/auth-navbar";
import "../././globals.css";
// Layout component for authentication pages
export const metadata: Metadata = {
  title: "Auth Layout",
  description: "Generated by create next app for Auth Layout",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <main className="max-w-2xl mx-auto p-4">
          {/* auth navbar */}
          <AuthNavbar />
          {children}
          {/* // auth footer */}
          <footer
            style={{
              marginTop: "2rem",
              textAlign: "center",
              fontSize: "0.8rem",
              color: "#666",
            }}
          >
            <p>© 2023 My App. All rights reserved.</p>
          </footer>
        </main>
      </body>
    </html>
  );
}
