import type { Metadata } from "next";
import "../globals.css";
export const metadata: Metadata = {
  title: { default: "Shop Layout", template: "%s | Shop Layout" },
  description: "Generated by create next app for Shop Layout",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        {/* app header */}
        <header className="p-4 border-b mb-8 shadow-sm bg-green-600 text-red-400">
          <nav>
            <h1>Shop Layout</h1>
          </nav>
        </header>
        {children}
        {/* app footer */}
        <footer className="p-4 border-t mt-8 shadow-sm bg-gray-600 text-center text-red-400">
          <p>© 2024 Shop. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}
